language: c

compiler:
    - gcc
    - clang

install:
    - sudo apt-get update
    - sudo apt-get install cmake valgrind

script:
    - mkdir _build
    - cd _build
    - cmake ..
    - make

after_success:
    - valgrind --tool=memcheck --leak-check=yes ./linked-list
