language: c

compiler:
    - gcc
    - clang

install:
    - sudo apt-get update
    - sudo apt-get install cmake valgrind

after_success:
    - valgrind --tool=memcheck --leak-check=full ./linked-list
