language: c

compiler:
    - gcc
    - clang

install:
    - sudo apt-get update
    - sudo apt-get install cmake valgrind

script:
    - mkdir _build
    - cd _build

after_success:
    - valgrind --leak-check=yes
